services:
  hello-cpp-ubuntu-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: hello-cpp-ubuntu-dev:latest  # 构建后镜像的名称和标签
    environment:
      USER: root
    volumes:
      - .:/root/hello-cpp # 项目代码
      - ~/.ssh:/root/.ssh # 挂载以确保容器中可以提交代码
    working_dir: /root/hello-cpp
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: sleep infinity